#!/usr/bin/env bash

# shellcheck disable=SC2034

# Basic info
PN=mihomo
PV=1.18.2
P="${PN}-${PV}"
#S=${P}
SOURCE_DATE_EPOCH=1709827227
SRC_URI="https://github.com/MetaCubeX/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"
SRC_SHA256SUM="49855c53e5717932b9cb933e7f42f58155b52a42bf7db7f35f1fb1d4baa7ee00 ${P}.tar.gz"

config_src_unpack() {
	tar -xf "${P}".tar.gz
}

# Actions
GEN_GO_DEPS=1
