#!/usr/bin/env bash

# shellcheck disable=SC2034

# Basic info
PN=mihomo
PV=1.19.11
P="${PN}-${PV}"
#S=${P}
SOURCE_DATE_EPOCH=1751644827
SRC_URI="https://github.com/MetaCubeX/${PN}/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"
SRC_SHA256SUM="72730aff2c89f1cba60bfc9318e17ac8161db4e6c69bd24b54eb37f9fa646540 ${P}.tar.gz"

config_src_unpack() {
	tar -xf "${P}".tar.gz
}

# Actions
GEN_GO_DEPS=1
